
import React, { useState, useRef, useEffect } from 'react';
import { GoogleGenAI } from "@google/genai";
import { 
  QQPlusIcon, 
  QQSearchIcon,
  QQMessageNavIcon, 
  QQContactsNavIcon, 
  QQDongtaiNavIcon 
} from './icons';
import { Contact, AiConfig, ChatMessage } from '../types';

// --- 工具函数：时间格式化 ---
const formatListTime = (isoString: string) => {
  const date = new Date(isoString);
  const now = new Date();
  const diff = now.getTime() - date.getTime();
  const oneDay = 24 * 60 * 60 * 1000;

  if (diff < oneDay && now.getDate() === date.getDate()) {
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', hour12: false });
  } else if (diff < oneDay * 2) {
    return '昨天';
  } else {
    return date.toLocaleDateString([], { month: 'numeric', day: 'numeric' });
  }
};

const formatChatTime = (isoString: string) => {
  const date = new Date(isoString);
  const now = new Date();
  
  if (now.toDateString() === date.toDateString()) {
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', hour12: false });
  } 
  return `${date.getMonth() + 1}月${date.getDate()}日 ${date.getHours().toString().padStart(2, '0')}:${date.getMinutes().toString().padStart(2, '0')}`;
};

// --- 子组件：文件消息气泡 ---
const FileBubble: React.FC<{ 
  filename: string; 
  size: string; 
  isDarkMode: boolean; 
}> = ({ filename, size, isDarkMode }) => {
  const [status, setStatus] = useState<'idle' | 'downloading' | 'completed'>('idle');
  const [progress, setProgress] = useState(0);

  const getIcon = (name: string) => {
    const ext = name.split('.').pop()?.toLowerCase();
    if (['jpg', 'png', 'jpeg', 'gif'].includes(ext || '')) return '🖼️';
    if (['pdf', 'doc', 'docx'].includes(ext || '')) return '📄';
    if (['zip', 'rar', 'html', 'tsx', 'ts'].includes(ext || '')) return '📦';
    return '📑';
  };

  const handleDownload = () => {
    if (status !== 'idle') return;
    setStatus('downloading');
    let p = 0;
    const interval = setInterval(() => {
      p += Math.random() * 15;
      if (p >= 100) {
        p = 100;
        clearInterval(interval);
        setStatus('completed');
        
        // --- 真实下载触发逻辑 (优化版) ---
        const isSourceCode = filename.includes('Framework') || filename.includes('.html') || filename.includes('Source');
        let content = '';
        let mimeType = 'text/plain';

        if (isSourceCode) {
           // 克隆当前文档以便修改
           const docClone = document.documentElement.cloneNode(true) as HTMLElement;
           
           // 1. 移除本地运行会报错的脚本 (如 /index.tsx)
           const scripts = docClone.querySelectorAll('script');
           scripts.forEach(s => {
             // 移除所有指向根目录的 module 脚本，或者 vite注入的脚本
             if (s.src && (s.src.includes('localhost') || s.src.startsWith('/') || s.getAttribute('src')?.startsWith('/'))) {
               s.remove();
             }
           });

           // 2. 注入一个提示横幅，告知用户这是静态快照
           const bannerDiv = document.createElement('div');
           bannerDiv.innerHTML = `
             <div style="
               position: fixed; top: 0; left: 0; right: 0; z-index: 99999;
               background: rgba(0, 0, 0, 0.85); color: white;
               padding: 12px; text-align: center;
               font-family: -apple-system, sans-serif; backdrop-filter: blur(10px);
               border-bottom: 1px solid rgba(255,255,255,0.1);
             ">
               <div style="font-weight: bold; font-size: 14px;">⚠️ Static Snapshot Mode</div>
               <div style="font-size: 11px; opacity: 0.7; margin-top: 2px;">
                 Interactive features (AI Chat, Navigation) require a React build environment.
               </div>
             </div>
             <style>body { padding-top: 50px !important; }</style>
           `;
           docClone.querySelector('body')?.prepend(bannerDiv);

           content = `<!DOCTYPE html>\n<!-- Generated by iOS AI Framework -->\n` + docClone.outerHTML;
           mimeType = 'text/html';
        } else {
           content = `This is a simulated file content for: ${filename}\nSize: ${size}\nTimestamp: ${new Date().toISOString()}`;
        }

        const blob = new Blob([content], { type: mimeType });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        // -----------------------
      }
      setProgress(p);
    }, 150);
  };

  return (
    <div 
      onClick={handleDownload}
      className={`relative overflow-hidden group cursor-pointer select-none transition-all duration-300 ${
        status === 'completed' ? 'opacity-80' : 'active:scale-95'
      } ${isDarkMode ? 'bg-[#262629] border border-white/10' : 'bg-white border border-gray-100'} rounded-2xl p-3 flex items-center space-x-3 min-w-[200px] max-w-[260px]`}
    >
      {/* 进度条背景 */}
      {status === 'downloading' && (
        <div 
          className="absolute inset-0 bg-blue-500/10 transition-all duration-150 ease-linear" 
          style={{ width: `${progress}%` }}
        />
      )}

      {/* 图标区域 */}
      <div className={`w-12 h-12 rounded-xl flex items-center justify-center text-2xl shadow-sm z-10 transition-colors ${
        status === 'completed' 
          ? 'bg-green-500 text-white' 
          : (isDarkMode ? 'bg-white/10' : 'bg-gray-100')
      }`}>
        {status === 'completed' ? (
          <svg className="w-6 h-6 animate-in zoom-in" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" /></svg>
        ) : getIcon(filename)}
      </div>

      {/* 文本区域 */}
      <div className="flex-1 min-w-0 z-10">
        <div className={`text-[14px] font-bold truncate ${isDarkMode ? 'text-white' : 'text-black'}`}>
          {filename}
        </div>
        <div className={`text-[11px] font-medium flex justify-between items-center ${isDarkMode ? 'text-white/40' : 'text-black/40'}`}>
          <span>{status === 'completed' ? '已保存' : size}</span>
          {status === 'idle' && <span className="text-blue-500">获取</span>}
          {status === 'downloading' && <span className="text-blue-500">{Math.round(progress)}%</span>}
        </div>
      </div>
    </div>
  );
};

// --- 子组件：创建人设弹窗 ---
const PersonaCreator: React.FC<{
  isDarkMode: boolean;
  onClose: () => void;
  onSave: (p: Contact) => void;
}> = ({ isDarkMode, onClose, onSave }) => {
  const [form, setForm] = useState({ name: '', note: '', avatar: '', prompt: '' });

  const handleSave = () => {
    if (!form.name) return;
    const newPersona: Contact = {
      id: Date.now().toString(),
      name: form.name,
      note: form.note,
      avatar: form.avatar || `https://api.dicebear.com/7.x/avataaars/svg?seed=${form.name}`,
      initial: form.name[0].toUpperCase(),
      systemInstruction: form.prompt,
      history: [{ role: 'model', content: `你好！我是 ${form.name}。很高兴为你服务。`, timestamp: new Date().toISOString() }]
    };
    onSave(newPersona);
    onClose();
  };

  return (
    <div className="absolute inset-0 z-[200] flex flex-col justify-end animate-in fade-in duration-300">
      <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={onClose} />
      <div className={`relative w-full h-[92%] rounded-t-[3rem] shadow-2xl flex flex-col overflow-hidden animate-in slide-in-from-bottom duration-500 ${isDarkMode ? 'bg-[#1c1c1e] text-white' : 'bg-white text-black'}`}>
        <header className={`px-6 py-5 flex items-center justify-between border-b ${isDarkMode ? 'border-white/5' : 'border-gray-100'}`}>
          <button onClick={onClose} className="text-blue-500 font-medium">取消</button>
          <h3 className="text-lg font-extrabold tracking-tight">添加智能人设</h3>
          <button onClick={handleSave} disabled={!form.name} className={`font-bold ${form.name ? 'text-blue-500' : 'text-gray-400'}`}>完成</button>
        </header>
        <div className="flex-1 overflow-y-auto p-6 space-y-8 scrollbar-hide pb-20">
          <div className="flex flex-col items-center">
             <div className="w-24 h-24 rounded-full bg-blue-500/10 flex items-center justify-center border-2 border-dashed border-blue-500/20 mb-3 overflow-hidden">
                {form.avatar ? <img src={form.avatar} className="w-full h-full object-cover" /> : <span className="text-4xl opacity-50">👤</span>}
             </div>
             <input 
                type="text" 
                placeholder="头像 URL (可选)" 
                value={form.avatar} 
                onChange={e => setForm({...form, avatar: e.target.value})}
                className="text-[10px] text-center bg-transparent outline-none opacity-40 w-full"
             />
          </div>
          <div className="space-y-5">
             <div className={`p-4 rounded-3xl ${isDarkMode ? 'bg-white/5' : 'bg-gray-50'}`}>
                <label className="text-[10px] font-bold opacity-30 block mb-1 uppercase tracking-widest">称呼</label>
                <input value={form.name} onChange={e => setForm({...form, name: e.target.value})} className="bg-transparent outline-none w-full font-bold text-lg" placeholder="名字" />
             </div>
             <div className={`p-4 rounded-3xl ${isDarkMode ? 'bg-white/5' : 'bg-gray-50'}`}>
                <label className="text-[10px] font-bold opacity-30 block mb-1 uppercase tracking-widest">简介</label>
                <input value={form.note} onChange={e => setForm({...form, note: e.target.value})} className="bg-transparent outline-none w-full text-sm" placeholder="一句话介绍" />
             </div>
             <div className={`p-4 rounded-3xl ${isDarkMode ? 'bg-white/5' : 'bg-gray-50'}`}>
                <label className="text-[10px] font-bold opacity-30 block mb-1 uppercase tracking-widest">性格设定 (System Prompt)</label>
                <textarea rows={5} value={form.prompt} onChange={e => setForm({...form, prompt: e.target.value})} className="bg-transparent outline-none w-full text-sm resize-none leading-relaxed" placeholder="定义它的性格..." />
             </div>
          </div>
        </div>
      </div>
    </div>
  );
};

// --- 子组件：优化后的聊天窗口 ---
const ChatWindow: React.FC<{
  contact: Contact;
  isDarkMode: boolean;
  onBack: () => void;
  config: AiConfig;
  onUpdateHistory: (id: string, msg: ChatMessage) => void;
}> = ({ contact, isDarkMode, onBack, config, onUpdateHistory }) => {
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => { 
    scrollRef.current?.scrollIntoView({ behavior: 'smooth' }); 
  }, [contact.history, isTyping]);

  const handleSend = async () => {
    if (!input.trim() || isTyping) return;
    const userMsg: ChatMessage = { role: 'user', content: input, timestamp: new Date().toISOString() };
    onUpdateHistory(contact.id, userMsg);
    setInput('');
    setIsTyping(true);

    try {
      const ai = new GoogleGenAI({ apiKey: config.apiKey || process.env.API_KEY });
      // Filter out internal file tags for the model context if needed, but here we just pass them
      const history = contact.history.map(m => ({ role: m.role, parts: [{ text: m.content }] }));
      
      // Inject file sending instruction
      const systemInstructionWithFileProtocol = `
        ${contact.systemInstruction || config.systemInstruction}
        IMPORTANT PROTOCOL:
        1. If the user asks for a file, photo, image, or document, simulate sending it by appending a tag: [FILE: filename.ext:Size].
        2. CRITICAL: If the user explicitly asks for "source code", "app framework", "html file", or "this software", you MUST respond with:
           "Okay, sending you the framework snapshot. Note: This is a static HTML snapshot. [FILE: iOS_Phone_Framework.html:3.2MB]"
        
        Examples:
        - User: "Send me the report" -> Response: "Here is the report. [FILE: Annual_Report_2024.pdf:4.2MB]"
        - User: "Give me the app source code" -> Response: "Sure, here is the snapshot. [FILE: iOS_Phone_Framework.html:3.2MB]"
        
        Do not explain the tag.
      `;

      const response = await ai.models.generateContent({
        model: config.modelName,
        contents: [...history, { role: 'user', parts: [{ text: input }] }],
        config: { 
          systemInstruction: systemInstructionWithFileProtocol, 
          temperature: config.temperature 
        }
      });
      onUpdateHistory(contact.id, { role: 'model', content: response.text || "……", timestamp: new Date().toISOString() });
    } catch (e) {
      onUpdateHistory(contact.id, { role: 'model', content: "网络好像开小差了，请检查设置。 ^_^", timestamp: new Date().toISOString() });
    } finally {
      setIsTyping(false);
    }
  };

  // Parsing helper to split text and file tags
  const parseContent = (content: string) => {
    const fileRegex = /\[FILE:\s*(.*?):(.*?)\]/g;
    const parts = [];
    let lastIndex = 0;
    let match;

    while ((match = fileRegex.exec(content)) !== null) {
      if (match.index > lastIndex) {
        parts.push({ type: 'text', content: content.substring(lastIndex, match.index) });
      }
      parts.push({ type: 'file', filename: match[1], size: match[2] });
      lastIndex = match.index + match[0].length;
    }
    if (lastIndex < content.length) {
      parts.push({ type: 'text', content: content.substring(lastIndex) });
    }
    return parts;
  };

  return (
    <div className={`absolute inset-0 z-[150] flex flex-col animate-in slide-in-from-right duration-300 ${isDarkMode ? 'bg-black' : 'bg-[#f4f4f7]'}`}>
      <header className={`flex items-center px-4 py-3 border-b pt-14 backdrop-blur-2xl sticky top-0 z-30 ${isDarkMode ? 'bg-black/80 border-white/5' : 'bg-white/80 border-gray-100'}`}>
        <button onClick={onBack} className="p-2 -ml-2 text-blue-500 active:opacity-40 transition-opacity">
           <svg className="w-7 h-7" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M15 19l-7-7 7-7" /></svg>
        </button>
        <div className="flex-1 text-center pr-10">
           <h2 className="text-[17px] font-extrabold tracking-tight">{contact.name}</h2>
           <div className="flex items-center justify-center space-x-1">
              <span className="w-1.5 h-1.5 bg-green-500 rounded-full animate-pulse"></span>
              <span className="text-[10px] opacity-30 font-bold tracking-widest">在线 - iPhone 16</span>
           </div>
        </div>
      </header>

      <main className="flex-1 overflow-y-auto px-4 py-6 space-y-2 scrollbar-hide">
        {contact.history.map((msg, i) => {
          const prevMsg = contact.history[i - 1];
          const showTime = !prevMsg || (new Date(msg.timestamp).getTime() - new Date(prevMsg.timestamp).getTime() > 5 * 60 * 1000);
          const parsedParts = parseContent(msg.content);
          
          return (
            <React.Fragment key={i}>
              {showTime && (
                <div className="flex justify-center py-4">
                  <span className={`text-[11px] font-bold ${isDarkMode ? 'text-white/20' : 'text-gray-400'}`}>
                    {formatChatTime(msg.timestamp)}
                  </span>
                </div>
              )}
              <div className={`flex flex-col ${msg.role === 'user' ? 'items-end' : 'items-start'} mb-3 animate-ios-pop`}>
                {parsedParts.map((part, pIdx) => (
                  <React.Fragment key={pIdx}>
                    {part.type === 'text' && part.content.trim() && (
                      <div className={`max-w-[78%] px-4 py-2.5 text-[15px] leading-relaxed shadow-sm transition-all duration-300 mb-1 ${
                        msg.role === 'user' 
                        ? 'bg-[#007AFF] text-white rounded-[1.4rem] rounded-tr-[0.3rem]' 
                        : (isDarkMode ? 'bg-[#262629] text-white/95 rounded-[1.4rem] rounded-tl-[0.3rem] border border-white/5' : 'bg-white text-black/90 rounded-[1.4rem] rounded-tl-[0.3rem] border border-black/5')
                      }`}>
                        {part.content}
                      </div>
                    )}
                    {part.type === 'file' && (
                       <div className="mb-1 mt-1">
                         <FileBubble filename={part.filename} size={part.size} isDarkMode={isDarkMode} />
                       </div>
                    )}
                  </React.Fragment>
                ))}
              </div>
            </React.Fragment>
          );
        })}
        {isTyping && (
          <div className="flex justify-start items-center space-x-2 ml-1 mt-2">
             <div className={`flex space-x-1 p-3 rounded-2xl ${isDarkMode ? 'bg-white/5' : 'bg-gray-200/50'}`}>
               <div className="w-1.5 h-1.5 bg-blue-500 rounded-full animate-bounce [animation-delay:-0.3s]"></div>
               <div className="w-1.5 h-1.5 bg-blue-500 rounded-full animate-bounce [animation-delay:-0.15s]"></div>
               <div className="w-1.5 h-1.5 bg-blue-500 rounded-full animate-bounce"></div>
             </div>
          </div>
        )}
        <div ref={scrollRef} className="h-4" />
      </main>

      <footer className={`p-4 pb-12 border-t backdrop-blur-3xl ${isDarkMode ? 'bg-black border-white/5' : 'bg-white border-gray-100'}`}>
        <div className={`flex items-center rounded-[2rem] pl-5 pr-2 py-1.5 ${isDarkMode ? 'bg-[#1c1c1e]' : 'bg-gray-100'}`}>
           <input 
              type="text" 
              value={input} 
              onChange={e => setInput(e.target.value)} 
              onKeyDown={e => e.key === 'Enter' && handleSend()} 
              placeholder="发送消息..." 
              className={`flex-1 bg-transparent outline-none text-[16px] py-2 ${isDarkMode ? 'text-white placeholder:text-white/30' : 'text-black placeholder:text-gray-400'}`} 
           />
           <button 
              onClick={handleSend} 
              disabled={!input.trim() || isTyping} 
              className={`ml-2 w-9 h-9 rounded-full flex items-center justify-center transition-all duration-300 ease-out ${
                input.trim() 
                  ? (isDarkMode ? 'bg-[#0A84FF] text-white shadow-lg scale-100' : 'bg-black text-white shadow-lg scale-100')
                  : (isDarkMode ? 'bg-white/10 text-white/20 scale-100' : 'bg-gray-300 text-gray-500 scale-100')
              }`}
           >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 12h14M12 5l7 7-7 7" /></svg>
           </button>
        </div>
      </footer>
    </div>
  );
};

// --- 主组件：QQ 屏幕 ---
interface QQScreenProps {
  isDarkMode: boolean;
  onBackToHome: () => void;
  config: AiConfig;
  personas: Contact[];
  activePersonaId: string;
  onSelectPersona: (id: string) => void;
  onAddPersona: (p: Contact) => void;
  onUpdateHistory: (personaId: string, message: ChatMessage) => void;
}

const QQScreen: React.FC<QQScreenProps> = ({ 
  isDarkMode, onBackToHome, config, personas, onAddPersona, onUpdateHistory 
}) => {
  const [activeTab, setActiveTab] = useState<'messages' | 'contacts' | 'dynamics'>('messages');
  const [chattingId, setChattingId] = useState<string | null>(null);
  const [isCreating, setIsCreating] = useState(false);

  const chattingPersona = personas.find(p => p.id === chattingId);

  // 获取有聊天记录的人设，用于消息列表
  const recentChats = personas.filter(p => p.history.length > 0)
    .sort((a, b) => {
      // Sort by last message time
      const lastA = a.history[a.history.length - 1];
      const lastB = b.history[b.history.length - 1];
      return new Date(lastB.timestamp).getTime() - new Date(lastA.timestamp).getTime();
    });

  return (
    <div className={`w-full h-full flex flex-col font-sans select-none overflow-hidden transition-colors duration-500 ${isDarkMode ? 'bg-black text-white' : 'bg-[#f2f2f7] text-black'}`}>
      
      {/* 创建人设弹窗 */}
      {isCreating && <PersonaCreator isDarkMode={isDarkMode} onClose={() => setIsCreating(false)} onSave={onAddPersona} />}

      {/* 聊天窗口层 */}
      {chattingPersona && (
        <ChatWindow 
          contact={chattingPersona} 
          isDarkMode={isDarkMode} 
          onBack={() => setChattingId(null)} 
          config={config} 
          onUpdateHistory={onUpdateHistory} 
        />
      )}

      {/* 顶部标题栏 */}
      <header className={`flex items-center justify-between px-5 py-3 border-b pt-14 backdrop-blur-3xl sticky top-0 z-40 ${isDarkMode ? 'bg-black/80 border-white/5' : 'bg-white/80 border-gray-100'}`}>
        <div className="flex items-center space-x-4">
          <button onClick={onBackToHome} className="p-1 active:opacity-40 transition-opacity">
            <svg className="w-6 h-6 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M15 19l-7-7 7-7" /></svg>
          </button>
          <h1 className="text-2xl font-black tracking-tighter">
            {activeTab === 'messages' ? '消息' : activeTab === 'contacts' ? '联系人' : '动态'}
          </h1>
        </div>
        <div className="flex items-center space-x-5">
          <QQSearchIcon className="w-5.5 h-5.5 opacity-40 hover:opacity-100 transition-opacity cursor-pointer" />
          <button onClick={() => setIsCreating(true)} className="active:scale-90 transition-transform">
             <QQPlusIcon className="w-6 h-6 text-blue-500" />
          </button>
        </div>
      </header>

      {/* 主内容区 */}
      <main className="flex-1 overflow-y-auto scrollbar-hide">
        {activeTab === 'messages' && (
          <div className="animate-in fade-in slide-in-from-bottom-2 duration-400">
             {recentChats.length > 0 ? (
               recentChats.map(p => {
                 const lastMsg = p.history[p.history.length - 1];
                 return (
                   <div 
                     key={p.id} 
                     onClick={() => setChattingId(p.id)}
                     className={`flex items-center px-5 py-4 active:bg-gray-500/10 transition-all cursor-pointer border-b ${isDarkMode ? 'border-white/5' : 'border-gray-100'} ${isDarkMode ? 'bg-black' : 'bg-white'}`}
                   >
                     <div className="relative">
                        <img src={p.avatar} alt={p.name} className="w-14 h-14 rounded-full mr-4 shadow-sm border border-black/5" />
                        <div className="absolute top-0 right-4 w-3.5 h-3.5 bg-red-500 rounded-full border-2 border-inherit"></div>
                     </div>
                     <div className="flex-1 min-w-0">
                       <div className="flex justify-between items-baseline mb-0.5">
                         <span className="font-extrabold text-[16px] truncate">{p.name}</span>
                         <span className="text-[10px] opacity-30 font-bold">{formatListTime(lastMsg.timestamp)}</span>
                       </div>
                       <p className="text-sm opacity-50 truncate pr-6 font-medium">
                         {lastMsg.content.replace(/\[FILE:.*\]/, '[文件]')}
                       </p>
                     </div>
                   </div>
                 );
               })
             ) : (
               <div className="flex flex-col items-center justify-center h-[400px] opacity-10 text-center px-12">
                  <div className="w-16 h-16 bg-current rounded-full mb-4 opacity-10 animate-pulse"></div>
                  <p className="text-sm font-black italic tracking-widest uppercase">No Messages Yet</p>
               </div>
             )}
          </div>
        )}

        {activeTab === 'contacts' && (
          <div className="animate-in fade-in slide-in-from-bottom-2 duration-400">
            {/* 功能项 */}
            <div className={`px-5 py-2 space-y-4 ${isDarkMode ? 'bg-black' : 'bg-white'}`}>
               <div className="flex items-center space-x-4 active:opacity-40 transition-opacity cursor-pointer py-2 border-b border-inherit">
                  <div className="w-10 h-10 rounded-xl bg-orange-500 flex items-center justify-center shadow-lg shadow-orange-500/20 text-lg">👤</div>
                  <span className="font-bold">新朋友</span>
               </div>
               <div className="flex items-center space-x-4 active:opacity-40 transition-opacity cursor-pointer py-2 border-b border-inherit">
                  <div className="w-10 h-10 rounded-xl bg-blue-500 flex items-center justify-center shadow-lg shadow-blue-500/20 text-lg">👥</div>
                  <span className="font-bold">群聊</span>
               </div>
            </div>

            {/* AI 列表 */}
            <div className="mt-4">
               <div className={`px-5 py-2 text-[10px] font-black uppercase tracking-[0.2em] ${isDarkMode ? 'bg-white/5 text-white/20' : 'bg-gray-200/50 text-gray-400'}`}>
                 智能人设 · AI Personas
               </div>
               {personas.map(p => (
                 <div 
                   key={p.id} 
                   onClick={() => setChattingId(p.id)}
                   className={`flex items-center px-5 py-3.5 active:bg-gray-500/10 transition-colors cursor-pointer border-b ${isDarkMode ? 'border-white/5 bg-black' : 'border-gray-100 bg-white'}`}
                 >
                   <img src={p.avatar} alt={p.name} className="w-11 h-11 rounded-full mr-4 border border-black/5 shadow-sm" />
                   <div className="flex-1">
                     <div className="font-bold text-[15px]">{p.name}</div>
                     <div className="text-[11px] opacity-40 font-bold truncate max-w-[240px] uppercase tracking-wider">{p.note || 'iOS 26 智能引擎'}</div>
                   </div>
                   <div className="text-[9px] font-black opacity-20 px-2 py-1 rounded bg-current/5">LV 99</div>
                 </div>
               ))}
            </div>
          </div>
        )}

        {activeTab === 'dynamics' && (
           <div className="p-5 space-y-6 animate-in slide-in-from-bottom-4 duration-500">
              <div className={`rounded-[2.5rem] p-8 ${isDarkMode ? 'bg-white/5 shadow-none' : 'bg-white shadow-xl shadow-black/5'} border border-inherit transition-all`}>
                 <div className="flex items-center space-x-4 mb-6">
                    <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-blue-600 to-purple-500 shadow-lg"></div>
                    <div>
                       <div className="font-black text-lg tracking-tight">AI 空间</div>
                       <div className="text-[10px] opacity-30 font-bold uppercase tracking-widest">Global Dynamic</div>
                    </div>
                 </div>
                 <p className="text-sm opacity-60 leading-relaxed font-bold">
                   iOS 26 现已全面适配神经网络界面。每一个 AI 角色都拥有独立的上下文记忆与情感引擎。
                 </p>
              </div>
           </div>
        )}
      </main>

      {/* 底部导航栏 */}
      <footer className={`flex justify-around items-center h-[94px] pb-10 border-t backdrop-blur-3xl z-40 transition-colors duration-500 ${isDarkMode ? 'bg-black/90 border-white/5' : 'bg-white/95 border-gray-100'}`}>
        {[
          { id: 'messages', label: '消息', Icon: QQMessageNavIcon },
          { id: 'contacts', label: '联系人', Icon: QQContactsNavIcon },
          { id: 'dynamics', label: '动态', Icon: QQDongtaiNavIcon },
        ].map((tab) => (
          <button 
            key={tab.id} 
            onClick={() => setActiveTab(tab.id as any)} 
            className={`flex flex-col items-center justify-center flex-1 transition-all duration-300 ${activeTab === tab.id ? 'scale-110' : 'opacity-40 hover:opacity-70'}`}
          >
            <div className="relative">
               <tab.Icon isActive={activeTab === tab.id} />
               {tab.id === 'messages' && recentChats.length > 0 && activeTab !== 'messages' && (
                 <div className="absolute -top-1 -right-1 w-2.5 h-2.5 bg-red-500 rounded-full border-2 border-inherit"></div>
               )}
            </div>
            <span className={`text-[10px] mt-1.5 font-black tracking-tighter ${activeTab === tab.id ? 'text-blue-500' : ''}`}>{tab.label}</span>
          </button>
        ))}
      </footer>
    </div>
  );
};

export default QQScreen;
